---
chdir: /srv/www/admin.onlynet.biz.staging/current
#environment: production
environment: development
address: 0.0.0.0
port: 6010
timeout: 30
log: log/thin.staging.log
pid: tmp/pids/thin.staging.pid
max_conns: 1024
max_persistent_conns: 100
require: []
wait: 30
daemonize: true
