---
chdir: /srv/www/admin.onlynet.biz/current
environment: production
#environment: development
address: 0.0.0.0
port: 5010
timeout: 30
log: log/thin.log
pid: tmp/pids/thin.pid
max_conns: 1024
max_persistent_conns: 100
require: []
wait: 30
daemonize: true
